[[Singular]]
arch = "aarch64"
git-tree-sha1 = "efdd1dd7c05ed7b85bd682b7b81d12a9d4ada13b"
os = "macos"

    [[Singular.download]]
    sha256 = "dcd664845a13a07b8de2f98ede3eee5b12ff432d02b5da46ba7c03823484f0c1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8717672c34f4ea6239432a96d4e3c182a583fd98"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "1b7bdba2de44d3f6ccc7beaf71e00785646f94bbb4ddab3dfd29ac4260efb58d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a4f8f6ec6650552a57e6cb63ac3a4e0a046f842"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "1a5f4763ac7e325d7e25307d0c7c29a6a900d83c322f783efa255e739d10a1ed"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "d9709437861f441f427eed18b879eefdcac3ce79"
os = "freebsd"

    [[Singular.download]]
    sha256 = "f71081cd783915cc8dcbe2aba954540cb8e530093e6a3b760ac38f6e44cf4a08"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03e46afa790f45ca720444fbc5710bb30cb07c6a"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "d6342af0380f00dbb8d9ae7e6074704598b573216dd6925b25a750a7fd82fb64"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78b398a991b7c254052a087930a65cd6add93961"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "fb968875240d0c63c8624767a663326f61b17e2b299234ac76f614f46c782c1d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e977fb1e050540fcbb1bd4443ea200bbff4dcca9"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "b2c6f902b4fa2f0aaaae399a7d4a5eb5b2b923b4e42cf7dfae6c69c47a7bd0dc"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66808e1cfefa0cd2e89dff35d8d1fc52dc257315"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "5f2558a484cbdd58f04a982b89c0a175da2b7beea7bbe3b7ffa398edfad2e1b1"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3128c1e584ff313523546a1c268a93fca146e04"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "8ef90825c423febeb31a30bddcbf70d32a0c0313183d1a75b5715d054957cd3f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ccba82a28a4bd2ef0c89cc22c07dae08ca3ac81"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "5b09d938e3726532683808e4813ac5d4a57d0c47b906d1480629cf91ad6b8eda"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e7694f85df36237b400c1f02f9390f9328b95d5"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "edb8b6884db275f5ea89f0464b6c241bc32acc0e77f3e899219ffea6f92ff065"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "679030ec6a5b408c2c06240d6e51c6d8ee6b9b34"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "24b8a8f6370e536ee4d4330ad3d157d7b0b48e25c1158f90046346ec8719f839"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "fde4edd8e763af0e8751fcdd9faf8213ef4a17cf"
os = "macos"

    [[Singular.download]]
    sha256 = "2293e2b1b5463b1a5fdac5401035bb98dad3bc0c6a78540b76711225acacd2b5"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4aeb143b742e7c1276b9c84b018a1f3f9314c270"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ca8a6ebe9d55c227f32d012c7cfffcadb2aefe80756476e2072f113e986fe3d6"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca52f60a0d7f958d5b47bce2e975e59de1f06e5e"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "0c4f1d7e059a7018c186a154b339a332713e45a175981c5877db33368a135fe4"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "ce913595e5d30e59ee0d3651084ba67dfa871895"
os = "freebsd"

    [[Singular.download]]
    sha256 = "c27e337709eaf45da0d5c14917756894cf6d512807c7a5c63fe73cb837bad4c2"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+0/Singular.v404.101.505.x86_64-unknown-freebsd.tar.gz"
