[[Singular]]
arch = "aarch64"
git-tree-sha1 = "aa1dc2ec8f387d1204b3794c074ba439d6ea371b"
os = "macos"

    [[Singular.download]]
    sha256 = "1c956ebc35229a5ec86fdf48f53dcfd6450bee638421f26ed29c97516c41ae4b"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c4b8117e6079ce9af2d6fb9b6b6f40b2fa8636c"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "f34162a7b0475a4f2dbf2bbee079bed7ae32fc7550c7e31d03c6543518049b11"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c614ca4938a9d0616b0425b2480d20697292cb93"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "9a91bcddd56d17837acf82a18a5ca20b9d32b918b5a553192b2ac1d4b6b72a55"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "1fffd6e2d586407c3da9bc3ef3273fee88c750ad"
os = "freebsd"

    [[Singular.download]]
    sha256 = "5117a8663de46698faf130001838ae4351d174168424cd86254326093eee15c5"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd4c3de23f3e3e3f524765545893aad85ba8b5da"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "9005bc1bf2309b90ceae69e231b792d0759cf96ab0365a64e2f9a4c4e629e62f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "124d6ff5d6098ca1e2f5c08170bdf9bd3a29013c"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "c2ad11e7b18deeaf17c0ce526be08a3a763e58bdba42c0eb1deff26e6f62cae8"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b116e50bca69dcdcb420d62640c1f6d20a7d6adb"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ba1d1d25f0e34ae3608cca804a09c53ee707dd025991dc3a1e236a36cc1abe84"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c22118db8f325de5d89706052c3f8cb888b7fe02"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "ae6883799a955bb9d16be38ceb6cb9f8cfac636c1833b28937f032ecf1a61a59"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acc14a76e1f9340a854c3e6097b3778c5ff6525c"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "a0056548bc6460e698651e22c8cff5c10746fdf91221aa38f0d232a2c9858a91"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4490d81642a7090a29ce0bffc746d50a55be903"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "53a3ccebabaf87fc718f76881a0b61b424c348d53f720dd70887ecd9e4922a92"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3663ba5844f70a82c9944ceccd1c0d5dc170f271"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "4eb8192940fb45c257a5bcee9f109928931c5c144cb346bbfd94906c7526dd6c"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d08482d940a02633f0b2e5dcc780042ec5e35977"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "ff49c6375c004b51cda3c47f0e5ec1078a35deda226b6609e3acb1eca06c2802"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "54d95d1ab86248aa1eac36fd4fad50515cdef55c"
os = "macos"

    [[Singular.download]]
    sha256 = "386dbef4ebccb16dc6c5ef9d77bf4c189fca3157956bd416ddf501c9d0a1dcf2"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4800c5b306d81852ffd3448381fa16722f7cd423"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "8e3616381c861d768683c0f36aee23f6d08c9488e0046aacdafb511d02ca521f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0f344237447af6f82660734e7afa7bd4f101b47"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "e6898e1e993776d51edf93bfb1a5aa1e1c84d5d2e02ff94e6a4db667fdae061e"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "0af2d620b906e9ab83475d50f3761c42cf8f0a3e"
os = "freebsd"

    [[Singular.download]]
    sha256 = "b62f97e8825bfc6db482162470e7f358eae2cc237a720bfca771768b2812d501"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.505+2/Singular.v404.101.505.x86_64-unknown-freebsd.tar.gz"
