[[Singular]]
arch = "aarch64"
git-tree-sha1 = "982000837972bc07a09b1a3efa1be34adaf8884c"
os = "macos"

    [[Singular.download]]
    sha256 = "0ed7ebdf177d715ebdee9228dba867bc96dfdfdd569d1654dbac6c7491928492"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.aarch64-apple-darwin.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3c96c9dffdbee16d7ae3ccd1b80b50b5dbbc49a"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "20c0802a9035b6734e52afec7799d1d7c91a1858e764abfe38350c62acd277d6"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.aarch64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5a81e1cddad98b5da96336f53d2899da6dc6696"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "eec430435a1ff9927daca026f915292ccca724249b7cace5c806ab566af2cbd3"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.aarch64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "aarch64"
git-tree-sha1 = "019aa50e3882818b0497992fbee6f23b75c53300"
os = "freebsd"

    [[Singular.download]]
    sha256 = "d81a0783e417af9d743660df9c5fe00c79c1c2adce6a88ce9977c33a1c44f76d"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.aarch64-unknown-freebsd.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30c138db8a2dad98fa2d0bd61fdd9bc6f04f3875"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "6b5976a79fb51a02aed00be02c1cef83959d2c853c3c08d76581d9bbc79013c3"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a3c69b1ca54f18f632a900ab10c47278ffb1da4"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "c3bb099d630ad6a17a96c46bec8b9a1fc50a3c7fb62bc4f2ef04ba131b3559ca"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "666db8160f5be8c2c91599eabd9299201e46b836"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "e17cd5d06458e016c6977a08d8a6f5306eb409815bfba843c05df63257385238"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Singular]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6debefdc56ccd9487120e7e2d0831498c41ddbff"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "6e1fd7210bc078c301ecabf15d0b6cad85f5586088a300152c1d2c7f35fb472f"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "223a2f6499f712eaf1ca57aa894de340633e083b"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "57647d90798764b98cf7f51ee4ba468628a5959d99bc442145ab706c52381410"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.i686-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cda74da9e7d45f1324e19c4bf6f209abffc3e12"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "0ec822a6649b66fc0646fb1867d8c59274dbb7e9c1493644e074fc8dd0cc8edb"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.i686-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d602b7cc7f179d5f6eefda864d850b5da9b48a1e"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "d557886bc0b4bf8c4114efeaf1f2a52582dbe5142b51e5cda56571d82f970600"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff84f20b9431271032e37156d7bdd9af0f0782f6"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "94dea062b10cb36aee94417741846141e168bb3545d26397f35fd8238cc7b255"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.riscv64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "ed00d42f5a03d06658fef9f8ef21054b1f4232b1"
os = "macos"

    [[Singular.download]]
    sha256 = "5368907d9a52a7d74362a0295a86bd5ec3b5a86230b98e8e505580e2c68d6fd3"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.x86_64-apple-darwin.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb4ab5e50bc99a966679dada7384a3898c8eab5a"
libc = "glibc"
os = "linux"

    [[Singular.download]]
    sha256 = "2f27bad2bb5b3d5ddd21765593c40db360148017563f2768f61e986ee0fd2c3b"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.x86_64-linux-gnu-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5813d657830a08cff8ed92a76efb73017ee28fe3"
libc = "musl"
os = "linux"

    [[Singular.download]]
    sha256 = "bb63949894ccf8e66208142291d8af28d48a1f455fc92421185493842aee7dd8"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.x86_64-linux-musl-cxx11.tar.gz"
[[Singular]]
arch = "x86_64"
git-tree-sha1 = "a6809551c43042113c5c65ede2b220b55adb14de"
os = "freebsd"

    [[Singular.download]]
    sha256 = "aae16fc713a4f90b39c42f9324a070e2a45df1c5af11ec518bee68b8e7b1513a"
    url = "https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/download/Singular-v404.101.507+0/Singular.v404.101.507.x86_64-unknown-freebsd.tar.gz"
